### pandas

> pandas is a powerfull python library for manipulation and analysis of data

>its a open source library 

>fast(built on top of numpy),flexible(differnt resource),productive library

In [1]:
pip install pandas

Defaulting to user installation because normal site-packages is not writeable
Requirement already satisfied: pandas in c:\programdata\anaconda3\lib\site-packages (2.2.3)
Requirement already satisfied: numpy>=1.26.0 in c:\programdata\anaconda3\lib\site-packages (from pandas) (2.1.3)
Requirement already satisfied: python-dateutil>=2.8.2 in c:\programdata\anaconda3\lib\site-packages (from pandas) (2.9.0.post0)
Requirement already satisfied: pytz>=2020.1 in c:\programdata\anaconda3\lib\site-packages (from pandas) (2024.1)
Requirement already satisfied: tzdata>=2022.7 in c:\programdata\anaconda3\lib\site-packages (from pandas) (2025.2)
Requirement already satisfied: six>=1.5 in c:\programdata\anaconda3\lib\site-packages (from python-dateutil>=2.8.2->pandas) (1.17.0)
Note: you may need to restart the kernel to use updated packages.

In [2]:
import pandas as pd

In [3]:
print(pd.__version__)

2.2.3

### series - one dimensional array(data structure)with lable

In [4]:
l1 = [1,2,3,4,5]
type(l1)

list

In [5]:
s=pd.Series(l1,index = ["a","b","c","d","e"],name = "My series")

In [6]:
s

a    1
b    2
c    3
d    4
e    5
Name: My series, dtype: int64

In [7]:
s['a']

np.int64(1)

In [8]:
s=pd.Series(l1,index = ["apple","cherry","mango","banana","watermel"],name = "My Series")

In [9]:
s

apple       1
cherry      2
mango       3
banana      4
watermel    5
Name: My Series, dtype: int64

In [10]:
type(s)

pandas.core.series.Series

In [11]:
s.index

Index(['apple', 'cherry', 'mango', 'banana', 'watermel'], dtype='object')

In [12]:
s.values

array([1, 2, 3, 4, 5])

>Note : Index in series imuutable(cant change)

In [13]:
s.index[0] ='z'

TypeError: Index does not support mutable operations

In [ ]:
### changing the index of pandas series

s = s.rename(index = {'b':'y'})

In [ ]:
s

apple       1
cherry      2
mango       3
banana      4
watermel    5
Name: My Series, dtype: int64

In [ ]:

s.rename(index = {'b':'y'},inplace = True)

 # dataframe - its a 2d array (just like tables)

In [ ]:
dict1 = {'Name':['virat','rohit','dhoni','jadeja' ,'bumrah'],
         'Age':[23,32,43,53,33], 
         'Marks':[65,66,67,68,69],
         'Role':['batsman','batsman','wicketkeeper','all rounder','bowler']}

pd.DataFrame(dict1)

     Name  Age  Marks          Role
0   virat   23     65       batsman
1   rohit   32     66       batsman
2   dhoni   43     67  wicketkeeper
3  jadeja   53     68   all rounder
4  bumrah   33     69        bowler

In [ ]:
df=pd.DataFrame(dict1)

In [ ]:
type(df)

pandas.core.frame.DataFrame

In [ ]:
df

     Name  Age  Marks          Role
0   virat   23     65       batsman
1   rohit   32     66       batsman
2   dhoni   43     67  wicketkeeper
3  jadeja   53     68   all rounder
4  bumrah   33     69        bowler

In [ ]:
df.tail

<bound method NDFrame.tail of      Name  Age  Marks          Role
0   virat   23     65       batsman
1   rohit   32     66       batsman
2   dhoni   43     67  wicketkeeper
3  jadeja   53     68   all rounder
4  bumrah   33     69        bowler>

In [ ]:
df.head(2)

    Name  Age  Marks     Role
0  virat   23     65  batsman
1  rohit   32     66  batsman

In [ ]:
df.count

<bound method DataFrame.count of      Name  Age  Marks          Role
0   virat   23     65       batsman
1   rohit   32     66       batsman
2   dhoni   43     67  wicketkeeper
3  jadeja   53     68   all rounder
4  bumrah   33     69        bowler>

In [ ]:
len(df)

5

In [ ]:
df.columns

Index(['Name', 'Age', 'Marks', 'Role'], dtype='object')

In [ ]:
type(df['Name'])

pandas.core.series.Series

In [ ]:
df['Name'].value_counts()

Name
virat     1
rohit     1
dhoni     1
jadeja    1
bumrah    1
Name: count, dtype: int64

#### Basic operations

> Importing data set from different files


> Importing tablar data set

In [17]:
pd.read_csv(r"C:\Users\klemp\Desktop\data analys(ms)\Data set\ETH_1h.csv")

                   Date  Symbol    Open    High     Low   Close      Volume
0      2020-03-13 08-PM  ETHUSD  129.94  131.82  126.87  128.71  1940673.93
1      2020-03-13 07-PM  ETHUSD  119.51  132.02  117.10  129.94  7579741.09
2      2020-03-13 06-PM  ETHUSD  124.47  124.85  115.50  119.51  4898735.81
3      2020-03-13 05-PM  ETHUSD  124.08  127.42  121.63  124.47  2753450.92
4      2020-03-13 04-PM  ETHUSD  124.85  129.51  120.17  124.08  4461424.71
...                 ...     ...     ...     ...     ...     ...         ...
23669  2017-07-01 03-PM  ETHUSD  265.74  272.74  265.00  272.57  1500282.55
23670  2017-07-01 02-PM  ETHUSD  268.79  269.90  265.00  265.74  1702536.85
23671  2017-07-01 01-PM  ETHUSD  274.83  274.93  265.00  268.79  3010787.99
23672  2017-07-01 12-PM  ETHUSD  275.01  275.01  271.00  274.83   824362.87
23673  2017-07-01 11-AM  ETHUSD  279.98  279.99  272.10  275.01   679358.87

[23674 rows x 7 columns]

In [18]:
stock_df =pd.read_csv(r"C:\Users\klemp\Desktop\data analys(ms)\Data set\ETH_1h.csv")

In [19]:
stock_df

                   Date  Symbol    Open    High     Low   Close      Volume
0      2020-03-13 08-PM  ETHUSD  129.94  131.82  126.87  128.71  1940673.93
1      2020-03-13 07-PM  ETHUSD  119.51  132.02  117.10  129.94  7579741.09
2      2020-03-13 06-PM  ETHUSD  124.47  124.85  115.50  119.51  4898735.81
3      2020-03-13 05-PM  ETHUSD  124.08  127.42  121.63  124.47  2753450.92
4      2020-03-13 04-PM  ETHUSD  124.85  129.51  120.17  124.08  4461424.71
...                 ...     ...     ...     ...     ...     ...         ...
23669  2017-07-01 03-PM  ETHUSD  265.74  272.74  265.00  272.57  1500282.55
23670  2017-07-01 02-PM  ETHUSD  268.79  269.90  265.00  265.74  1702536.85
23671  2017-07-01 01-PM  ETHUSD  274.83  274.93  265.00  268.79  3010787.99
23672  2017-07-01 12-PM  ETHUSD  275.01  275.01  271.00  274.83   824362.87
23673  2017-07-01 11-AM  ETHUSD  279.98  279.99  272.10  275.01   679358.87

[23674 rows x 7 columns]

In [21]:
stock_df.head()

               Date  Symbol    Open    High     Low   Close      Volume
0  2020-03-13 08-PM  ETHUSD  129.94  131.82  126.87  128.71  1940673.93
1  2020-03-13 07-PM  ETHUSD  119.51  132.02  117.10  129.94  7579741.09
2  2020-03-13 06-PM  ETHUSD  124.47  124.85  115.50  119.51  4898735.81
3  2020-03-13 05-PM  ETHUSD  124.08  127.42  121.63  124.47  2753450.92
4  2020-03-13 04-PM  ETHUSD  124.85  129.51  120.17  124.08  4461424.71

In [22]:
stock_df.head(10)

               Date  Symbol    Open    High     Low   Close      Volume
0  2020-03-13 08-PM  ETHUSD  129.94  131.82  126.87  128.71  1940673.93
1  2020-03-13 07-PM  ETHUSD  119.51  132.02  117.10  129.94  7579741.09
2  2020-03-13 06-PM  ETHUSD  124.47  124.85  115.50  119.51  4898735.81
3  2020-03-13 05-PM  ETHUSD  124.08  127.42  121.63  124.47  2753450.92
4  2020-03-13 04-PM  ETHUSD  124.85  129.51  120.17  124.08  4461424.71
5  2020-03-13 03-PM  ETHUSD  128.39  128.90  116.06  124.85  7378976.00
6  2020-03-13 02-PM  ETHUSD  134.03  137.90  125.50  128.39  3733916.89
7  2020-03-13 01-PM  ETHUSD  131.35  140.95  128.99  134.03  9582732.93
8  2020-03-13 12-PM  ETHUSD  128.93  134.60  126.95  131.35  3906590.52
9  2020-03-13 11-AM  ETHUSD  132.60  133.17  126.01  128.93  3311080.29

In [23]:
stock_df.head() #top 5 rows

               Date  Symbol    Open    High     Low   Close      Volume
0  2020-03-13 08-PM  ETHUSD  129.94  131.82  126.87  128.71  1940673.93
1  2020-03-13 07-PM  ETHUSD  119.51  132.02  117.10  129.94  7579741.09
2  2020-03-13 06-PM  ETHUSD  124.47  124.85  115.50  119.51  4898735.81
3  2020-03-13 05-PM  ETHUSD  124.08  127.42  121.63  124.47  2753450.92
4  2020-03-13 04-PM  ETHUSD  124.85  129.51  120.17  124.08  4461424.71

## Bottom 5 rows

In [24]:
stock_df.tail()

                   Date  Symbol    Open    High    Low   Close      Volume
23669  2017-07-01 03-PM  ETHUSD  265.74  272.74  265.0  272.57  1500282.55
23670  2017-07-01 02-PM  ETHUSD  268.79  269.90  265.0  265.74  1702536.85
23671  2017-07-01 01-PM  ETHUSD  274.83  274.93  265.0  268.79  3010787.99
23672  2017-07-01 12-PM  ETHUSD  275.01  275.01  271.0  274.83   824362.87
23673  2017-07-01 11-AM  ETHUSD  279.98  279.99  272.1  275.01   679358.87

In [25]:
## Number of rows in dataframe

len(stock_df)

23674

## Access column names of dataframe

In [26]:
stock_df.columns

Index(['Date', 'Symbol', 'Open', 'High', 'Low', 'Close', 'Volume'], dtype='object')

In [28]:
## acessing column in a dataframe
stock_df['Open']

0        129.94
1        119.51
2        124.47
3        124.08
4        124.85
          ...
23669    265.74
23670    268.79
23671    274.83
23672    275.01
23673    279.98
Name: Open, Length: 23674, dtype: float64

In [29]:
stock_df['Close']

0        128.71
1        129.94
2        119.51
3        124.47
4        124.08
          ...
23669    272.57
23670    265.74
23671    268.79
23672    274.83
23673    275.01
Name: Close, Length: 23674, dtype: float64

In [32]:
## Accessing multiple columns in a dataframe

stock_df[['Open','Close','Volume']]

         Open   Close      Volume
0      129.94  128.71  1940673.93
1      119.51  129.94  7579741.09
2      124.47  119.51  4898735.81
3      124.08  124.47  2753450.92
4      124.85  124.08  4461424.71
...       ...     ...         ...
23669  265.74  272.57  1500282.55
23670  268.79  265.74  1702536.85
23671  274.83  268.79  3010787.99
23672  275.01  274.83   824362.87
23673  279.98  275.01   679358.87

[23674 rows x 3 columns]

### Accessing  rows of dataframe

In [33]:
stock_df.index

RangeIndex(start=0, stop=23674, step=1)

In [34]:
l=[1,2,3,4]

In [35]:
l

[1, 2, 3, 4]

In [36]:
l=[1,2,3,4,'hello',True]

##  Accesssing rows

loc-labal location

In [ ]:
stock_df.loc[23672]

Date      2017-07-01 12-PM
Symbol              ETHUSD
Open                275.01
High                275.01
Low                  271.0
Close               274.83
Volume           824362.87
Name: 23672, dtype: object

In [39]:
stock_df.loc[23672,'Date']

'2017-07-01 12-PM'

In [40]:
stock_df.loc[23672,['Date','Open','Close']]

Date     2017-07-01 12-PM
Open               275.01
Close              274.83
Name: 23672, dtype: object

In [41]:
stock_df['Open']

0        129.94
1        119.51
2        124.47
3        124.08
4        124.85
          ...
23669    265.74
23670    268.79
23671    274.83
23672    275.01
23673    279.98
Name: Open, Length: 23674, dtype: float64

In [42]:
l=[1,2,3,4,5]
l[1:4] #slicing a list

[2, 3, 4]

In [56]:
d2 = [[1,2,3],
      [4,5,6],
      [7,8,9]]
d2=np.array(d2)

In [57]:
d2

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [58]:
d2[1]

array([4, 5, 6])

In [50]:
import numpy as np

In [60]:
d2[0,1]

np.int64(2)

In [63]:
d2[1][2]

np.int64(6)

###  slicing in loc (labeled location)

df.loc['roe_label1':'row_label_3','column_label_1':'column_label_2']

In [65]:
stock_df.loc[23672,'Open':'Close']

Open     275.01
High     275.01
Low       271.0
Close    274.83
Name: 23672, dtype: object

### iloc - index based location,when we dont know labels for rows andcolumns

In [103]:
stock_df

                   Date  Symbol    Open    High     Low   Close      Volume
0      2020-03-13 08-PM  ETHUSD  129.94  131.82  126.87  128.71  1940673.93
1      2020-03-13 07-PM  ETHUSD  119.51  132.02  117.10  129.94  7579741.09
2      2020-03-13 06-PM  ETHUSD  124.47  124.85  115.50  119.51  4898735.81
3      2020-03-13 05-PM  ETHUSD  124.08  127.42  121.63  124.47  2753450.92
4      2020-03-13 04-PM  ETHUSD  124.85  129.51  120.17  124.08  4461424.71
...                 ...     ...     ...     ...     ...     ...         ...
23669  2017-07-01 03-PM  ETHUSD  265.74  272.74  265.00  272.57  1500282.55
23670  2017-07-01 02-PM  ETHUSD  268.79  269.90  265.00  265.74  1702536.85
23671  2017-07-01 01-PM  ETHUSD  274.83  274.93  265.00  268.79  3010787.99
23672  2017-07-01 12-PM  ETHUSD  275.01  275.01  271.00  274.83   824362.87
23673  2017-07-01 11-AM  ETHUSD  279.98  279.99  272.10  275.01   679358.87

[23674 rows x 7 columns]

In [104]:
stock_df.iloc[1,]

Date      2020-03-13 07-PM
Symbol              ETHUSD
Open                119.51
High                132.02
Low                  117.1
Close               129.94
Volume          7579741.09
Name: 1, dtype: object

In [105]:
stock_df.iloc[2,2] # row index and column index

np.float64(124.47)

In [106]:
stock_df.iloc[2,2:6] # slicing of columns using iloc

Open     124.47
High     124.85
Low       115.5
Close    119.51
Name: 2, dtype: object

In [107]:
stock_df.iloc[3,[2,4]] # multiple column index

Open    124.08
Low     121.63
Name: 3, dtype: object

In [108]:
stock_df.iloc[2:5,2:6] #

     Open    High     Low   Close
2  124.47  124.85  115.50  119.51
3  124.08  127.42  121.63  124.47
4  124.85  129.51  120.17  124.08

In [109]:
stock_df.iloc[1:6,2:6]

     Open    High     Low   Close
1  119.51  132.02  117.10  129.94
2  124.47  124.85  115.50  119.51
3  124.08  127.42  121.63  124.47
4  124.85  129.51  120.17  124.08
5  128.39  128.90  116.06  124.85

## Filtering

In [125]:
stock_df['Date']

0        2020-03-13 08-PM
1        2020-03-13 07-PM
2        2020-03-13 06-PM
3        2020-03-13 05-PM
4        2020-03-13 04-PM
               ...
23669    2017-07-01 03-PM
23670    2017-07-01 02-PM
23671    2017-07-01 01-PM
23672    2017-07-01 12-PM
23673    2017-07-01 11-AM
Name: Date, Length: 23674, dtype: object

In [111]:
f1=stock_df['High'] > 130
stock_df[f1]

                   Date  Symbol    Open    High     Low   Close      Volume
0      2020-03-13 08-PM  ETHUSD  129.94  131.82  126.87  128.71  1940673.93
1      2020-03-13 07-PM  ETHUSD  119.51  132.02  117.10  129.94  7579741.09
6      2020-03-13 02-PM  ETHUSD  134.03  137.90  125.50  128.39  3733916.89
7      2020-03-13 01-PM  ETHUSD  131.35  140.95  128.99  134.03  9582732.93
8      2020-03-13 12-PM  ETHUSD  128.93  134.60  126.95  131.35  3906590.52
...                 ...     ...     ...     ...     ...     ...         ...
23669  2017-07-01 03-PM  ETHUSD  265.74  272.74  265.00  272.57  1500282.55
23670  2017-07-01 02-PM  ETHUSD  268.79  269.90  265.00  265.74  1702536.85
23671  2017-07-01 01-PM  ETHUSD  274.83  274.93  265.00  268.79  3010787.99
23672  2017-07-01 12-PM  ETHUSD  275.01  275.01  271.00  274.83   824362.87
23673  2017-07-01 11-AM  ETHUSD  279.98  279.99  272.10  275.01   679358.87

[21613 rows x 7 columns]

In [112]:
f1 = stock_df['High'] > 130
stock_gt_130 = stock_df[f1]

In [113]:
stock_gt_130.reset_index(drop=True,inplace=True)

In [114]:
stock_gt_130

                   Date  Symbol    Open    High     Low   Close      Volume
0      2020-03-13 08-PM  ETHUSD  129.94  131.82  126.87  128.71  1940673.93
1      2020-03-13 07-PM  ETHUSD  119.51  132.02  117.10  129.94  7579741.09
2      2020-03-13 02-PM  ETHUSD  134.03  137.90  125.50  128.39  3733916.89
3      2020-03-13 01-PM  ETHUSD  131.35  140.95  128.99  134.03  9582732.93
4      2020-03-13 12-PM  ETHUSD  128.93  134.60  126.95  131.35  3906590.52
...                 ...     ...     ...     ...     ...     ...         ...
21608  2017-07-01 03-PM  ETHUSD  265.74  272.74  265.00  272.57  1500282.55
21609  2017-07-01 02-PM  ETHUSD  268.79  269.90  265.00  265.74  1702536.85
21610  2017-07-01 01-PM  ETHUSD  274.83  274.93  265.00  268.79  3010787.99
21611  2017-07-01 12-PM  ETHUSD  275.01  275.01  271.00  274.83   824362.87
21612  2017-07-01 11-AM  ETHUSD  279.98  279.99  272.10  275.01   679358.87

[21613 rows x 7 columns]

In [115]:
len(stock_df)

23674

In [116]:
stock_df.index

RangeIndex(start=0, stop=23674, step=1)

In [117]:
stock_df.iloc[len(stock_df)-1]

Date      2017-07-01 11-AM
Symbol              ETHUSD
Open                279.98
High                279.99
Low                  272.1
Close               275.01
Volume           679358.87
Name: 23673, dtype: object

In [118]:
for i in range(0,3):
    print(i)

0
1
2

In [119]:
stock_df['Random_col'] = list(range(1,len(stock_df)+1))

In [120]:
stock_df

,Date,Symbol,Open,High,Low,Close,Volume,Random_col
0,2020-03-13 08-PM,ETHUSD,129.94,131.82,126.87,128.71,1940673.93,1
1,2020-03-13 07-PM,ETHUSD,119.51,132.02,117.10,129.94,7579741.09,2
2,2020-03-13 06-PM,ETHUSD,124.47,124.85,115.50,119.51,4898735.81,3
3,2020-03-13 05-PM,ETHUSD,124.08,127.42,121.63,124.47,2753450.92,4
4,2020-03-13 04-PM,ETHUSD,124.85,129.51,120.17,124.08,4461424.71,5
...,...,...,...,...,...,...,...,...
23669,2017-07-01 03-PM,ETHUSD,265.74,272.74,265.00,272.57,1500282.55,23670
23670,2017-07-01 02-PM,ETHUSD,268.79,269.90,265.00,265.74,1702536.85,23671
23671,2017-07-01 01-PM,ETHUSD,274.83,274.93,265.00,268.79,3010787.99,23672
23672,2017-07-01 12-PM,ETHUSD,275.01,275.01,271.00,274.83,824362.87,23673
23673,2017-07-01 11-AM,ETHUSD,279.98,279.99,272.10,275.01,679358.87,23674

## Dropping column

In [121]:
stock_df.drop(columns=['Random_col'],inplace=True)

In [123]:
stock_df

                   Date  Symbol    Open    High     Low   Close      Volume
0      2020-03-13 08-PM  ETHUSD  129.94  131.82  126.87  128.71  1940673.93
1      2020-03-13 07-PM  ETHUSD  119.51  132.02  117.10  129.94  7579741.09
2      2020-03-13 06-PM  ETHUSD  124.47  124.85  115.50  119.51  4898735.81
3      2020-03-13 05-PM  ETHUSD  124.08  127.42  121.63  124.47  2753450.92
4      2020-03-13 04-PM  ETHUSD  124.85  129.51  120.17  124.08  4461424.71
...                 ...     ...     ...     ...     ...     ...         ...
23669  2017-07-01 03-PM  ETHUSD  265.74  272.74  265.00  272.57  1500282.55
23670  2017-07-01 02-PM  ETHUSD  268.79  269.90  265.00  265.74  1702536.85
23671  2017-07-01 01-PM  ETHUSD  274.83  274.93  265.00  268.79  3010787.99
23672  2017-07-01 12-PM  ETHUSD  275.01  275.01  271.00  274.83   824362.87
23673  2017-07-01 11-AM  ETHUSD  279.98  279.99  272.10  275.01   679358.87

[23674 rows x 7 columns]

In [124]:
stock_df.drop(columns=['Open','High'],inplace=True)